# Generates js/metrics.js from the Carlito fonts and checks metric compatibility with a local Calibri.
import json, os, sys
from fontTools.ttLib import TTFont
def table(path):
    f = TTFont(path); cmap = f.getBestCmap(); hmtx = f["hmtx"]; upm = f["head"].unitsPerEm
    return {cp: hmtx[g][0] * 2048 // upm for cp, g in cmap.items() if cp < 0x2300 or cp in (0x25CF, 0x25A0)}, upm
reg, upm = table("fonts/Carlito-Regular.ttf"); bld, _ = table("fonts/Carlito-Bold.ttf")
print("unitsPerEm", upm, "glyphs kept", len(reg), len(bld))
out = "// Generated by test/gen_metrics.py from Carlito (SIL OFL). Advance widths in 1/2048 em.\nexport const METRICS = " + json.dumps(
    {"regular": {str(k): v for k, v in sorted(reg.items())}, "bold": {str(k): v for k, v in sorted(bld.items())}}, separators=(",", ":")) + ";\n"
open("js/metrics.js", "w", encoding="utf-8").write(out)
print("metrics.js bytes", len(out))
for name, mine, cal in (("regular", reg, r"C:\Windows\Fonts\calibri.ttf"), ("bold", bld, r"C:\Windows\Fonts\calibrib.ttf")):
    if not os.path.exists(cal): continue
    c, _ = table(cal)
    common = [cp for cp in mine if cp in c]
    diff = [cp for cp in common if mine[cp] != c[cp]]
    ascii_diff = [chr(cp) for cp in diff if cp < 0x250]
    print(name, "common", len(common), "differing", len(diff), "differing latin:", ascii_diff[:40])
